### ISSUE TITLE
New white-diamond-line symbol scaling issues ...

### ISSUE THREAD

**Issue by hholzgra** [waymarkedtrails/waymarkedtrails-shields#3]
We have several rotues in the area with a white diamond line label on black, and the actual route number inside the outline square. These were never rendered perfectly as the ref number partially overlapped with the diamond outline, esp. with two digit numbers, but was still somewhat readable.

With the new waymarkedtrails-sheets repository now, the diamond line aspect ration has changed, and symbol outline and text just get merged into an unreadable  filled white diamond blob ...

Symbol as used on the ground:

![raute-2](https://user-images.githubusercontent.com/451772/86015157-810cac80-ba21-11ea-8918-84e564469073.jpg)

Symbols as rendered by "old" waymarked-trails-site implementation:

![raute-2-old](https://user-images.githubusercontent.com/451772/86015359-c335ee00-ba21-11ea-8029-412b73c5cf93.png)

Symbols as rendered by "new" standalone waymarkedtrails-symbols repository: 

![raute-2-new](https://user-images.githubusercontent.com/451772/86015375-c7faa200-ba21-11ea-949a-8d04d242e480.png)

**Comment by hholzgra** [comment]
I'm probably going to replace the symbols with a literal "<2>", as I had planned for quite a while already (and the route operator is slowly changing the route symbols to more 'designed' symbols not compatible with OSMC descriptions anyway, so this isn't really urgent in any way ...

**Comment by lonvia** [comment]
Can you please add a reference to one of the relations and the osmc:symbol value.

**Comment by hholzgra** [comment]
Sure:

<2> with already experimentally changed osmc string: https://hiking.waymarkedtrails.org/#route?id=2168132

<4> single digit https://hiking.waymarkedtrails.org/#route?id=2092760

<10> double digit: https://hiking.waymarkedtrails.org/#route?id=2092759

**Comment by lonvia** [comment]
That's clearly a 'diamond' being rendered in the new style, not a diamond_line. AKA, a bug indeed.
